name = "blu-fitness"
compatibility_date = "2024-03-20"
account_id = "363ddf9846a01d1956a46bad97428cd3"

routes = [
  { pattern = "blu-fitness.boostsho.ir", custom_domain = true, zone_name = "boostsho.ir" },
  { pattern = "blu-fitness.ir", custom_domain = true, zone_name = "blu-fitness.ir" },
  { pattern = "www.blu-fitness.ir", custom_domain = true, zone_name = "blu-fitness.ir" }
]

[assets]
directory = "./"
